FROM openjdk:17-ea-14-jdk-alpine3.13

RUN apk add --no-cache inotify-tools

COPY dev/run.sh /script/run.sh
COPY transformations /transformations
RUN chmod a+x /script/run.sh

# get saxon
ARG SAXON_VERSION=10.3
ADD \
  https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar \
  /utils/saxon.jar
RUN chmod a+x /utils/saxon.jar

# get ddi profiles for cessda-cmv
ADD https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/1.0.4/profile.xml \
    /profiles/cdc/1.2.2.xml

ADD https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/1.0.4/profile.xml \
    /profiles/cdc/ddi-1.2.2-monolingual.xml

ADD https://cmv.cessda.eu/profiles/cdc/ddi-2.5/1.0.4/profile.xml \
    /profiles/cdc/ddi-2.5.xml

ADD https://cmv.cessda.eu/profiles/cdc/ddi-2.5/1.0.4/profile-mono.xml \
    /profiles/cdc/ddi-2.5-monolingual.xml

ADD https://cmv.cessda.eu/profiles/cdc/ddi-3.2/0.1.1/profile.xml \
    /profiles/cdc/ddi-3.2.xml

ADD https://cmv.cessda.eu/profiles/eqb/ddi-2.5/0.1.0/profile.xml \
    /profiles/eqb/ddi-2.5.xml

ADD https://cmv.cessda.eu/profiles/eqb/ddi-3.2/0.1.1/profile.xml \
    /profiles/eqb/ddi-3.2.xml

# get cessda-cmv-cmd
ARG CESSDA_CMV_CMD_VERSION=0.0.2
ADD \
  https://github.com/borsna/cessda-cmv-cmd/releases/download/${CESSDA_CMV_CMD_VERSION}/cmv-cmd.jar  \
  /utils/cmv-cmd.jar
RUN chmod a+x /utils/cmv-cmd.jar

ENTRYPOINT ["sh", "/script/run.sh"]